(* Tests for the signed transaction envelope (Tn_evm.Tx_envelope) and its strict
   decoder.

   Independent oracle: Tx_vectors, generated by an out-of-tree cargo project
   pinned to telcoin-network's own lock (alloy-consensus 1.8.3 / alloy-eips 1.8.3
   / alloy-primitives 1.5.7 / alloy-rlp 0.3.13). Fixture 1 reproduces the EIP-155
   specification's own published example byte for byte, so the fixture set is
   externally validated rather than self-referential; see tx_vectors.ml.

   The rejection and acceptance tables below are built from raw RLP chunks rather
   than from the fixtures, so that a non-canonical chunk (a leading-zero scalar,
   a 0x81 0x01 bool) can be injected: Rlp.encode_list concatenates
   already-encoded chunks and computes only the header. *)

module Tx_envelope = Tn_evm.Tx_envelope
module Tx_payload = Tn_evm.Tx_payload
module Tx_signature = Tn_evm.Tx_signature
module Transaction = Tn_evm.Transaction
module Block_roots = Tn_evm.Block_roots
module Rlp = Tn_rlp.Rlp
module U256 = Tn_state.U256
module Nonce = Tn_state.Nonce
module Address = Tn_types.Units.Address

let to_hex = Tx_vectors.to_hex
let b = Tx_vectors.hex

let envelope_of (c : Tx_vectors.case) =
  Tx_envelope.make ~payload:c.payload
    ~signature:
      (Tx_signature.make ~parity:c.parity ~r:(Tx_vectors.w_of_hex c.r)
         ~s:(Tx_vectors.w_of_hex c.s))

(* ------------------------------------------------------------------ *)
(* 1. Golden encode                                                    *)
(* ------------------------------------------------------------------ *)

let test_golden_encode () =
  List.iter
    (fun (c : Tx_vectors.case) ->
      let e = envelope_of c in
      Alcotest.(check string)
        (c.name ^ ": signing_payload") c.signing_payload
        (to_hex (Tx_envelope.signing_payload c.payload));
      Alcotest.(check string)
        (c.name ^ ": signature_hash") c.signing_hash
        (to_hex (Tx_envelope.signature_hash c.payload));
      Alcotest.(check string)
        (c.name ^ ": encode_2718") c.encoded_2718
        (to_hex (Tx_envelope.encode_2718 e));
      Alcotest.(check string) (c.name ^ ": hash") c.tx_hash (to_hex (Tx_envelope.hash e));
      Alcotest.(check string)
        (c.name ^ ": hash_of_2718 agrees with hash")
        c.tx_hash
        (to_hex (Tx_envelope.hash_of_2718 (b c.encoded_2718))))
    Tx_vectors.cases

(* ------------------------------------------------------------------ *)
(* 2. Golden decode — field by field, no wildcard arms                 *)
(* ------------------------------------------------------------------ *)

let kind_equal a c =
  match (a, c) with
  | Transaction.Call x, Transaction.Call y -> Address.equal x y
  | Transaction.Create, Transaction.Create -> true
  | Transaction.Call _, Transaction.Create | Transaction.Create, Transaction.Call _ -> false

let access_list_equal =
  List.equal (fun (a1, k1) (a2, k2) -> Address.equal a1 a2 && List.equal U256.equal k1 k2)

let variant_equal a c =
  match (a, c) with
  | Tx_payload.Legacy x, Tx_payload.Legacy y ->
      Option.equal U256.equal x.chain_id y.chain_id && U256.equal x.gas_price y.gas_price
  | Tx_payload.Eip2930 x, Tx_payload.Eip2930 y ->
      U256.equal x.chain_id y.chain_id && U256.equal x.gas_price y.gas_price
  | Tx_payload.Eip1559 x, Tx_payload.Eip1559 y ->
      U256.equal x.chain_id y.chain_id
      && U256.equal x.max_priority_fee_per_gas y.max_priority_fee_per_gas
      && U256.equal x.max_fee_per_gas y.max_fee_per_gas
  | Tx_payload.Legacy _, (Tx_payload.Eip2930 _ | Tx_payload.Eip1559 _) -> false
  | Tx_payload.Eip2930 _, (Tx_payload.Legacy _ | Tx_payload.Eip1559 _) -> false
  | Tx_payload.Eip1559 _, (Tx_payload.Legacy _ | Tx_payload.Eip2930 _) -> false

let payload_equal a c =
  variant_equal (Tx_payload.variant a) (Tx_payload.variant c)
  && Nonce.equal (Tx_payload.nonce a) (Tx_payload.nonce c)
  && Int.equal (Tx_payload.gas_limit a) (Tx_payload.gas_limit c)
  && kind_equal (Tx_payload.kind a) (Tx_payload.kind c)
  && U256.equal (Tx_payload.value a) (Tx_payload.value c)
  && String.equal (Tx_payload.data a) (Tx_payload.data c)
  && access_list_equal (Tx_payload.access_list a) (Tx_payload.access_list c)
  && Int.equal (Tx_payload.type_byte a) (Tx_payload.type_byte c)

let test_golden_decode () =
  List.iter
    (fun (c : Tx_vectors.case) ->
      let decoded = Tx_envelope.decode_2718 (b c.encoded_2718) in
      let ok =
        Result.fold ~error:(fun _ -> false)
          ~ok:(fun e ->
            payload_equal (Tx_envelope.payload e) c.payload
            && Bool.equal (Tx_signature.parity (Tx_envelope.signature e)) c.parity
            && U256.equal (Tx_signature.r (Tx_envelope.signature e)) (Tx_vectors.w_of_hex c.r)
            && U256.equal (Tx_signature.s (Tx_envelope.signature e)) (Tx_vectors.w_of_hex c.s))
          decoded
      in
      Alcotest.(check bool) (c.name ^ ": decode recovers every field") true ok)
    Tx_vectors.cases

(* ------------------------------------------------------------------ *)
(* 3. Round trip — the theorem the canonical-only accept set buys      *)
(* ------------------------------------------------------------------ *)

let test_round_trip () =
  let round (c : Tx_vectors.case) =
    Result.fold ~error:(fun _ -> "decode failed")
      ~ok:(fun e -> to_hex (Tx_envelope.encode_2718 e))
      (Tx_envelope.decode_2718 (b c.encoded_2718))
  in
  List.iter
    (fun (c : Tx_vectors.case) ->
      Alcotest.(check string) (c.name ^ ": encode_2718 . decode_2718 = id") c.encoded_2718 (round c))
    Tx_vectors.cases

(* ------------------------------------------------------------------ *)
(* Raw-chunk builders for the rejection / acceptance tables            *)
(* ------------------------------------------------------------------ *)

let to_a = Tx_vectors.to_a
let zero20 = String.make 40 '0'
let r32 = "a0" ^ String.make 64 '1'
let s32 = "a0" ^ String.make 64 '1'

(* A valid legacy envelope's nine chunks: nonce, gas_price, gas_limit, to, value,
   input, v, r, s. v = 0x1b = 27, i.e. parity false and no chain id. *)
let legacy_fields =
  [ b "80"; b "80"; b "825208"; b ("94" ^ to_a); b "80"; b "80"; b "1b"; b r32; b s32 ]

let legacy_of fields = Rlp.encode_list fields

(* A valid EIP-2930 envelope's eleven chunks. *)
let key32 = "a0" ^ String.make 64 '2'

let t1_fields =
  [
    b "01"; b "80"; b "80"; b "825208"; b ("94" ^ to_a); b "80"; b "80"; b "c0"; b "80"; b r32;
    b s32;
  ]

let t1_of fields = "\x01" ^ Rlp.encode_list fields

(* A valid EIP-1559 envelope's twelve chunks, in wire order: chain_id, nonce,
   max_priority_fee_per_gas, max_fee_per_gas, gas_limit, to, value, input,
   access_list, y_parity, r, s — the tip cap before the fee cap. *)
let t2_fields =
  [
    b "01"; b "80"; b "80"; b "80"; b "825208"; b ("94" ^ to_a); b "80"; b "80"; b "c0"; b "80";
    b r32; b s32;
  ]

let t2_of fields = "\x02" ^ Rlp.encode_list fields
let replace i v xs = List.mapi (fun j x -> if Int.equal j i then v else x) xs
let drop_last xs = List.filteri (fun j _ -> j < List.length xs - 1) xs
let al_of items = Rlp.encode_list items
let al_item addr keys = Rlp.encode_list [ b addr; Rlp.encode_list (List.map b keys) ]

let check_reject name bytes expected =
  Alcotest.(check string)
    name
    (Tx_envelope.error_to_string expected)
    (Result.fold ~ok:(fun _ -> "Ok (accepted)") ~error:Tx_envelope.error_to_string
       (Tx_envelope.decode_2718 bytes))

let check_accept name bytes =
  Alcotest.(check string)
    name "Ok (accepted)"
    (Result.fold ~ok:(fun _ -> "Ok (accepted)") ~error:Tx_envelope.error_to_string
       (Tx_envelope.decode_2718 bytes))

(* The signature scalars are RLP SCALARS, not fixed 32-byte strings: an envelope
   whose r or s is short must round-trip to its own shorter bytes, and its hash
   is a different hash. Every oracle fixture happens to have a full-width r and
   s, so nothing above would notice an encoder that wrote them fixed-width — this
   is where that choice is pinned. *)
let test_round_trip_short_scalars () =
  let round bytes =
    Result.fold ~error:Tx_envelope.error_to_string
      ~ok:(fun e -> to_hex (Tx_envelope.encode_2718 e))
      (Tx_envelope.decode_2718 bytes)
  in
  List.iter
    (fun (label, bytes) ->
      Alcotest.(check string) ("round trip: " ^ label) (to_hex bytes) (round bytes))
    [
      ("base legacy", legacy_of legacy_fields);
      ("base typed", t1_of t1_fields);
      ("r = 0", legacy_of (replace 7 (b "80") legacy_fields));
      ("one-byte r", legacy_of (replace 7 (b "01") legacy_fields));
      ("31-byte s", legacy_of (replace 8 (b ("9f" ^ String.make 62 '3')) legacy_fields));
      ("s = 0", legacy_of (replace 8 (b "80") legacy_fields));
      ("one-byte typed r", t1_of (replace 9 (b "01") t1_fields));
    ]

(* ------------------------------------------------------------------ *)
(* 4. The rejection table                                              *)
(* ------------------------------------------------------------------ *)

let test_base_vectors_decode () =
  check_accept "base legacy chunk vector decodes" (legacy_of legacy_fields);
  check_accept "base EIP-2930 chunk vector decodes" (t1_of t1_fields)

let test_reject_scalars () =
  check_reject "nonce 0x00" (legacy_of (replace 0 (b "00") legacy_fields))
    Tx_envelope.Leading_zero_scalar;
  check_reject "nonce 0x82 0x00 0x01" (legacy_of (replace 0 (b "820001") legacy_fields))
    Tx_envelope.Leading_zero_scalar;
  check_reject "nonce 9 bytes"
    (legacy_of (replace 0 (b ("89" ^ String.make 18 '1')) legacy_fields))
    Tx_envelope.Scalar_too_wide;
  check_reject "gas_price 17 bytes"
    (legacy_of (replace 1 (b ("91" ^ String.make 34 '1')) legacy_fields))
    Tx_envelope.Scalar_too_wide;
  check_reject "value 33 bytes"
    (legacy_of (replace 4 (b ("a1" ^ String.make 66 '1')) legacy_fields))
    Tx_envelope.Scalar_too_wide;
  check_reject "r 33 bytes"
    (legacy_of (replace 7 (b ("a1" ^ String.make 66 '1')) legacy_fields))
    Tx_envelope.Scalar_too_wide;
  check_reject "gas_limit = u64::MAX is unrepresentable here (documented narrowing)"
    (legacy_of (replace 2 (b "88ffffffffffffffff") legacy_fields))
    Tx_envelope.Unrepresentable_scalar

(* The width bounds on the TYPED readers are a separate code path from the legacy
   one above, and they are the port's only guard against accepting an integer
   alloy cannot hold: a chain id is a [u64] ([ChainId]) and the two EIP-1559 fee
   caps are [u128]. Nothing else in the suite reaches [read_eip1559]'s field
   readers with a malformed scalar, so without these the type-2 bounds could be
   deleted and every other test would still pass. *)
let test_reject_typed_scalars () =
  let wide n = b (Printf.sprintf "%02x%s" (0x80 + n) (String.make (2 * n) '1')) in
  (* chain_id is field 0 of both typed layouts; nine bytes exceeds a u64. *)
  check_reject "type 1: chain_id 9 bytes" (t1_of (replace 0 (wide 9) t1_fields))
    Tx_envelope.Scalar_too_wide;
  check_reject "type 2: chain_id 9 bytes" (t2_of (replace 0 (wide 9) t2_fields))
    Tx_envelope.Scalar_too_wide;
  (* The fee caps are fields 2 and 3; seventeen bytes exceeds a u128. *)
  check_reject "type 2: max_priority_fee_per_gas 17 bytes"
    (t2_of (replace 2 (wide 17) t2_fields))
    Tx_envelope.Scalar_too_wide;
  check_reject "type 2: max_fee_per_gas 17 bytes" (t2_of (replace 3 (wide 17) t2_fields))
    Tx_envelope.Scalar_too_wide;
  (* And the typed leading-zero rule, likewise unexercised on this path. *)
  check_reject "type 2: chain_id 0x00" (t2_of (replace 0 (b "00") t2_fields))
    Tx_envelope.Leading_zero_scalar;
  (* A sanity anchor: the unmodified type-2 skeleton these are derived from must
     itself decode, or every rejection above would pass for the wrong reason. *)
  check_accept "type 2: the unmodified skeleton decodes" (t2_of t2_fields)

let test_reject_shapes () =
  check_reject "to as 19 bytes"
    (legacy_of (replace 3 (b ("93" ^ String.make 38 '1')) legacy_fields))
    (Tx_envelope.Fixed_width { expected = 20; got = 19 });
  check_reject "to as a list" (legacy_of (replace 3 (b "c0") legacy_fields))
    Tx_envelope.Unexpected_list;
  check_reject "legacy list with 8 items"
    (legacy_of (drop_last legacy_fields))
    (Tx_envelope.Field_count { expected = 9; got = 8 });
  check_reject "legacy list with 10 items"
    (legacy_of (legacy_fields @ [ b "80" ]))
    (Tx_envelope.Field_count { expected = 9; got = 10 });
  check_reject "typed list with 10 items"
    (t1_of (drop_last t1_fields))
    (Tx_envelope.Field_count { expected = 11; got = 10 });
  check_reject "storage key as 31 bytes"
    (t1_of (replace 7 (al_of [ al_item ("94" ^ to_a) [ "9f" ^ String.make 62 '2' ] ]) t1_fields))
    (Tx_envelope.Fixed_width { expected = 32; got = 31 });
  check_reject "access list as a byte string"
    (t1_of (replace 7 (b "80") t1_fields))
    Tx_envelope.Unexpected_string;
  check_reject "access-list item with 3 fields"
    (t1_of
       (replace 7
          (al_of [ Rlp.encode_list [ b ("94" ^ to_a); Rlp.encode_list [ b key32 ]; b "80" ] ])
          t1_fields))
    (Tx_envelope.Field_count { expected = 2; got = 3 })

let test_reject_parity () =
  List.iter
    (fun (label, chunk) ->
      check_reject
        ("legacy v = " ^ label)
        (legacy_of (replace 6 (b chunk) legacy_fields))
        Tx_envelope.Invalid_parity_value)
    [
      ("0", "80"); ("1", "01"); ("26", "1a"); ("29", "1d"); ("34", "22");
      ("35 + 2*2^64 (chain id above u64::MAX)", "89020000000000000023");
    ];
  check_reject "typed y_parity 0x00"
    (t1_of (replace 8 (b "00") t1_fields))
    Tx_envelope.Leading_zero_scalar;
  check_reject "typed y_parity 0x02" (t1_of (replace 8 (b "02") t1_fields))
    Tx_envelope.Invalid_bool;
  check_reject "typed y_parity 0x81 0x01 (non-canonical single byte)"
    (t1_of (replace 8 (b "8101") t1_fields))
    (Tx_envelope.Rlp Rlp.Non_canonical_single_byte)

let test_reject_framing () =
  check_reject "empty input" "" Tx_envelope.Empty_input;
  check_reject "one trailing byte after a valid envelope"
    (legacy_of legacy_fields ^ "\x00")
    (Tx_envelope.Rlp Rlp.Trailing_bytes);
  check_reject "type byte 0x03 (EIP-4844)" ("\x03" ^ Rlp.encode_list t1_fields)
    (Tx_envelope.Unknown_type_byte 3);
  check_reject "type byte 0x05" ("\x05" ^ Rlp.encode_list t1_fields)
    (Tx_envelope.Unknown_type_byte 5);
  check_reject "type byte 0x7f" ("\x7f" ^ Rlp.encode_list t1_fields)
    (Tx_envelope.Unknown_type_byte 0x7f)

(* D-1: the two framings alloy accepts and this port deliberately refuses. Each
   re-hashes, in alloy, to the SAME transaction hash as its canonical twin — so
   accepting them would mean two byte strings sharing one hash. *)
let test_reject_non_canonical_framing () =
  check_reject "0x00-tagged legacy (alloy accepts; this port narrows)"
    ("\x00" ^ legacy_of legacy_fields)
    Tx_envelope.Zero_type_byte;
  check_reject "typed envelope behind an outer RLP string header (alloy accepts)"
    (Rlp.encode_bytes (t1_of t1_fields))
    Tx_envelope.Outer_string;
  check_reject "legacy envelope behind an outer RLP string header"
    (Rlp.encode_bytes (legacy_of legacy_fields))
    Tx_envelope.Outer_string;
  (* And the canonical twins are still accepted, so the rejection is about
     framing and nothing else. *)
  check_accept "the canonical legacy twin still decodes" (legacy_of legacy_fields);
  check_accept "the canonical typed twin still decodes" (t1_of t1_fields)

(* ------------------------------------------------------------------ *)
(* 5. Over-rejection guards: what a stricter decoder would fork on     *)
(* ------------------------------------------------------------------ *)

let test_must_accept () =
  check_accept "r = 0" (legacy_of (replace 7 (b "80") legacy_fields));
  check_accept "s = 0" (legacy_of (replace 8 (b "80") legacy_fields));
  check_accept "s >= n (all-ones)"
    (legacy_of (replace 8 (b ("a0" ^ String.make 64 'f')) legacy_fields));
  check_accept "s > secp256k1n/2 (high s decodes; recovery is where it fails)"
    (legacy_of (replace 8 (b "a0fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140")
                  legacy_fields));
  check_accept "legacy with no chain id (v = 27)" (legacy_of legacy_fields);
  check_accept "legacy chain_id = 0 (v = 35)" (legacy_of (replace 6 (b "23") legacy_fields));
  check_accept "legacy chain id exactly u64::MAX"
    (legacy_of (replace 6 (b "89020000000000000022") legacy_fields));
  check_accept "typed chain_id = 0" (t1_of (replace 0 (b "80") t1_fields));
  check_accept "access-list item with zero storage keys"
    (t1_of (replace 7 (al_of [ al_item ("94" ^ to_a) [] ]) t1_fields));
  check_accept "access list with duplicate addresses and repeated keys"
    (t1_of
       (replace 7
          (al_of
             [ al_item ("94" ^ to_a) [ key32; key32 ]; al_item ("94" ^ to_a) [ key32 ] ])
          t1_fields))

(* chain_id = Some 0 is NOT the same as None: the two differ in v and therefore
   in every byte downstream. *)
let test_chain_id_zero_distinct_from_none () =
  let decoded_chain_id bytes =
    Result.fold ~error:(fun _ -> None)
      ~ok:(fun e -> Tx_payload.chain_id (Tx_envelope.payload e))
      (Tx_envelope.decode_2718 bytes)
  in
  Alcotest.(check bool)
    "v = 27 gives no chain id" true
    (Option.is_none (decoded_chain_id (legacy_of legacy_fields)));
  Alcotest.(check bool)
    "v = 35 gives chain id Some 0" true
    (Option.equal U256.equal (Some U256.zero)
       (decoded_chain_id (legacy_of (replace 6 (b "23") legacy_fields))))

(* ------------------------------------------------------------------ *)
(* 6. Structural constants — the encodings a hand-written encoder gets *)
(*    wrong                                                            *)
(* ------------------------------------------------------------------ *)

let minimal_legacy ~kind ~data =
  Tx_payload.legacy ~nonce:(Tx_vectors.nonce_of 0) ~gas_price:U256.zero ~gas_limit:0 ~kind
    ~value:U256.zero ~data ~chain_id:None

let minimal_2930 ~access_list =
  Tx_payload.eip2930 ~chain_id:U256.zero ~nonce:(Tx_vectors.nonce_of 0) ~gas_price:U256.zero
    ~gas_limit:0 ~kind:Transaction.Create ~value:U256.zero ~data:"" ~access_list

let test_structural_constants () =
  let sp p = to_hex (Tx_envelope.signing_payload p) in
  Alcotest.(check string)
    "Create's `to` is the single byte 0x80" "c6808080808080"
    (sp (minimal_legacy ~kind:Transaction.Create ~data:""));
  Alcotest.(check string)
    "the zero address is 0x94 + twenty zero bytes, never 0x80"
    ("da808080" ^ "94" ^ zero20 ^ "8080")
    (sp (minimal_legacy ~kind:(Transaction.Call Address.zero) ~data:""));
  Alcotest.(check string)
    "one-byte calldata 0x2a is the bare byte" "c680808080802a"
    (sp (minimal_legacy ~kind:Transaction.Create ~data:"\x2a"));
  Alcotest.(check string)
    "one-byte calldata 0x80 is 0x81 0x80" "c780808080808180"
    (sp (minimal_legacy ~kind:Transaction.Create ~data:"\x80"));
  Alcotest.(check string)
    "an empty access list is the single byte 0xc0" "01c880808080808080c0"
    (sp (minimal_2930 ~access_list:[]));
  Alcotest.(check string)
    "an item with zero keys is d6 94 <20B> c0"
    ("01df80808080808080" ^ "d7d694" ^ zero20 ^ "c0")
    (sp (minimal_2930 ~access_list:[ (Address.zero, []) ]));
  Alcotest.(check string)
    "an item with one key sits exactly on the 55/56 payload boundary"
    ("01f84180808080808080" ^ "f838f794" ^ zero20 ^ "e1a0" ^ String.make 62 '0' ^ "01")
    (sp (minimal_2930 ~access_list:[ (Address.zero, [ U256.one ]) ]))

(* The two EIP-155 signing zeros are the NUMBER zero (0x80 0x80), and the tail is
   omitted entirely without a chain id. *)
let test_eip155_signing_tail () =
  Alcotest.(check string)
    "no chain id: six items, no tail" "c6808080808080"
    (to_hex (Tx_envelope.signing_payload (minimal_legacy ~kind:Transaction.Create ~data:"")));
  Alcotest.(check string)
    "chain id 0: nine items, tail 0x80 0x80 0x80" "c9808080808080808080"
    (to_hex
       (Tx_envelope.signing_payload
          (Tx_payload.legacy ~nonce:(Tx_vectors.nonce_of 0) ~gas_price:U256.zero ~gas_limit:0
             ~kind:Transaction.Create ~value:U256.zero ~data:"" ~chain_id:(Some U256.zero))))

(* ------------------------------------------------------------------ *)
(* 7. Transactions roots over real signed envelopes                    *)
(* ------------------------------------------------------------------ *)

let test_transactions_roots () =
  let envelopes = List.map envelope_of Tx_vectors.cases in
  List.iteri
    (fun i expected ->
      let prefix = List.filteri (fun j _ -> j <= i) envelopes in
      Alcotest.(check string)
        (Printf.sprintf "transactions_root_of over the first %d fixtures" (i + 1))
        expected
        (to_hex (Block_roots.transactions_root_of prefix));
      Alcotest.(check string)
        (Printf.sprintf "transactions_root_of = transactions_root . map encode_2718 (%d)" (i + 1))
        (to_hex (Block_roots.transactions_root (List.map Tx_envelope.encode_2718 prefix)))
        (to_hex (Block_roots.transactions_root_of prefix)))
    Tx_vectors.prefix_roots

let () =
  Alcotest.run "tx_envelope"
    [
      ( "encode",
        [
          Alcotest.test_case "golden signing payload, hash, 2718 bytes and tx hash" `Quick
            test_golden_encode;
          Alcotest.test_case "structural constants (to, calldata, access list)" `Quick
            test_structural_constants;
          Alcotest.test_case "the EIP-155 signing tail" `Quick test_eip155_signing_tail;
        ] );
      ( "decode",
        [
          Alcotest.test_case "base chunk vectors decode" `Quick test_base_vectors_decode;
          Alcotest.test_case "golden decode recovers every field" `Quick test_golden_decode;
          Alcotest.test_case "encode_2718 . decode_2718 = id" `Quick test_round_trip;
          Alcotest.test_case "round trip with short r/s (scalars, not fixed width)" `Quick
            test_round_trip_short_scalars;
          Alcotest.test_case "scalar canonicity and width" `Quick test_reject_scalars;
          Alcotest.test_case "typed scalar width (chain id, fee caps)" `Quick
            test_reject_typed_scalars;
          Alcotest.test_case "field shapes and counts" `Quick test_reject_shapes;
          Alcotest.test_case "parity values, legacy and typed" `Quick test_reject_parity;
          Alcotest.test_case "framing: empty, trailing, unknown type" `Quick test_reject_framing;
          Alcotest.test_case "non-canonical framings alloy accepts (D-1 narrowing)" `Quick
            test_reject_non_canonical_framing;
          Alcotest.test_case "must accept: no crypto validation at the RLP layer" `Quick
            test_must_accept;
          Alcotest.test_case "chain_id = Some 0 is distinct from None" `Quick
            test_chain_id_zero_distinct_from_none;
        ] );
      ( "roots",
        [
          Alcotest.test_case "transactions roots over every fixture prefix" `Quick
            test_transactions_roots;
        ] );
    ]
