(* Golden signed-transaction fixtures, generated by an out-of-tree cargo oracle
   pinned to telcoin-network's own lock: alloy-consensus 1.8.3 / alloy-eips 1.8.3
   / alloy-primitives 1.5.7 / alloy-rlp 0.3.13. Do not edit the hexes by hand.

   These are EXTERNALLY VALIDATED, not self-referential. Fixture 1 reproduces the
   EIP-155 specification's own published example byte for byte: signing payload
   ec098504a817c800825208943535353535353535353535353535353535353535
   880de0b6b3a764000080018080, signing hash daf5a779ae972f972197303d7b574746
   c7ef83eadac0f2791ad23db92e4c8e53, signed RLP f86c0985...6a3b6d83, sender
   0x9d8A62f656a8d1615C1294fd71e9CFb3E4855A4F. Everything else in the file comes
   from the same oracle run, so pinning one pins the encoder that produced the
   rest.

   Shared by test_tx_envelope and test_tx_recovery, as trie_vectors.ml is shared
   by the trie tests. *)

module Tx_payload = Tn_evm.Tx_payload
module Transaction = Tn_evm.Transaction
module U256 = Tn_state.U256
module Nonce = Tn_state.Nonce
module Address = Tn_types.Units.Address

(* ---- hex helpers, shared by both test executables ---- *)

let to_hex s =
  let buf = Buffer.create (2 * String.length s) in
  String.iter (fun c -> Buffer.add_string buf (Printf.sprintf "%02x" (Char.code c))) s;
  Buffer.contents buf

(* A hex digit's value; a non-hex character reads as zero, which no fixture
   contains. Written as arithmetic rather than a match so no arm is a
   wildcard. *)
let digit c =
  let n = Char.code c in
  if n >= Char.code '0' && n <= Char.code '9' then n - Char.code '0'
  else if n >= Char.code 'a' && n <= Char.code 'f' then n - Char.code 'a' + 10
  else if n >= Char.code 'A' && n <= Char.code 'F' then n - Char.code 'A' + 10
  else 0

let hex s =
  String.init
    (String.length s / 2)
    (fun i -> Char.chr ((digit s.[2 * i] lsl 4) lor digit s.[(2 * i) + 1]))

(* ---- constructors (every default below is unreachable by construction) ---- *)

let w_of_int n = Option.value ~default:U256.zero (U256.of_int n)

(* A big-endian hex literal of at most 32 bytes, left-padded to the width
   [of_be_bytes] accepts. *)
let w_of_hex h =
  let raw = hex h in
  Option.value ~default:U256.zero
    (U256.of_be_bytes (String.make (32 - String.length raw) '\000' ^ raw))

let addr h = Option.value ~default:Address.zero (Address.of_bytes (hex h))
let nonce_of n = Option.value ~default:Nonce.zero (Nonce.of_int n)

(* ---- the fixture inputs, transcribed from the oracle's source ---- *)

let to_a = "3535353535353535353535353535353535353535"
let to_b = "00000000000000000000000000000000000000ff"

(* sender(KEY) and sender(KEY2), lowercased. *)
let sender_key = "9d8a62f656a8d1615c1294fd71e9cfb3e4855a4f"
let sender_key2 = "9a2dfefe2bcc1c9c85b5d2c6afccf37e192516a4"

(* Two items, the second with NO storage keys, so the 0xc0 empty-key-list and
   the 0xd6 short item both appear in a golden. *)
let access_list_fixture =
  [
    (addr to_b, [ w_of_hex "01"; w_of_hex "ff" ]);
    (addr to_a, []);
  ]

type case = {
  name : string;
  payload : Tx_payload.t;
  parity : bool;
  r : string;  (** 32-byte big-endian, hex *)
  s : string;  (** 32-byte big-endian, hex *)
  signing_payload : string;  (** hex *)
  signing_hash : string;  (** hex *)
  encoded_2718 : string;  (** hex — the trie leaf and the tx-hash pre-image *)
  tx_hash : string;  (** hex *)
  sender : string;  (** 20-byte address, hex *)
}

let legacy_eip155_spec_vector =
  {
    name = "legacy_eip155_spec_vector";
    payload =
      Tx_payload.legacy ~nonce:(nonce_of 9)
        ~gas_price:(w_of_int 20_000_000_000)
        ~gas_limit:21_000
        ~kind:(Transaction.Call (addr to_a))
        ~value:(w_of_int 1_000_000_000_000_000_000)
        ~data:"" ~chain_id:(Some (w_of_int 1));
    parity = false;
    r = "28ef61340bd939bc2195fe537567866003e1a15d3c71ff63e1590620aa636276";
    s = "67cbe9d8997f761aecb703304b3800ccf555c9f3dc64214b297fb1966a3b6d83";
    signing_payload =
      "ec098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a764000080018080";
    signing_hash = "daf5a779ae972f972197303d7b574746c7ef83eadac0f2791ad23db92e4c8e53";
    encoded_2718 =
      "f86c098504a817c800825208943535353535353535353535353535353535353535880de0b6b3a76400008025a028ef61340bd939bc2195fe537567866003e1a15d3c71ff63e1590620aa636276a067cbe9d8997f761aecb703304b3800ccf555c9f3dc64214b297fb1966a3b6d83";
    tx_hash = "33469b22e9f636356c4160a87eb19df52b7412e8eac32a4a55ffe88ea8350788";
    sender = sender_key;
  }

let legacy_pre155_no_chain_id =
  {
    name = "legacy_pre155_no_chain_id";
    payload =
      Tx_payload.legacy ~nonce:(nonce_of 0)
        ~gas_price:(w_of_int 1_000_000_000)
        ~gas_limit:50_000
        ~kind:(Transaction.Call (addr to_b))
        ~value:(w_of_int 1) ~data:(hex "deadbeef") ~chain_id:None;
    parity = false;
    r = "24097f4982346c0c2b1e4acb85333b41af206c011c1b7a21e33ffb231173d28e";
    s = "3be269ca483803bf126bbd8c02553f32cca14ff77a07e0cfbff8246027244a43";
    signing_payload = "e480843b9aca0082c3509400000000000000000000000000000000000000ff0184deadbeef";
    signing_hash = "e4fe5135244a2b87b02bf836efe766f6935b204de1c51366367610a08f7406de";
    encoded_2718 =
      "f86780843b9aca0082c3509400000000000000000000000000000000000000ff0184deadbeef1ba024097f4982346c0c2b1e4acb85333b41af206c011c1b7a21e33ffb231173d28ea03be269ca483803bf126bbd8c02553f32cca14ff77a07e0cfbff8246027244a43";
    tx_hash = "ed677f0ce5d42176db758f08e70732de02d4936e9f46c893d3f099a23dea44a2";
    sender = sender_key2;
  }

let legacy_create =
  {
    name = "legacy_create";
    payload =
      Tx_payload.legacy ~nonce:(nonce_of 7) ~gas_price:(w_of_int 3) ~gas_limit:100_000
        ~kind:Transaction.Create ~value:U256.zero ~data:(hex "6001600053")
        ~chain_id:(Some (w_of_int 2017));
    parity = true;
    r = "cff201ad4ef180808bf6cd510294a6eb0b6d2cd6a233ee11657ea8f56bbeaf68";
    s = "155a1d6b3dcdac84a628badc5fcfeab1aabf62c66f8fd930e96ac6dd7915dbdf";
    signing_payload = "d30703830186a080808560016000538207e18080";
    signing_hash = "a0834e46d5c43d99a8e200a7d92eaabf533926814093ae2f58a931556cde6e54";
    encoded_2718 =
      "f8530703830186a08080856001600053820fe6a0cff201ad4ef180808bf6cd510294a6eb0b6d2cd6a233ee11657ea8f56bbeaf68a0155a1d6b3dcdac84a628badc5fcfeab1aabf62c66f8fd930e96ac6dd7915dbdf";
    tx_hash = "cdb35d707ad956aaff36034f0c2de57f7c0e5d8fab530aaa3f6e74dd795deb7e";
    sender = sender_key;
  }

let eip2930_with_access_list =
  {
    name = "eip2930_with_access_list";
    payload =
      Tx_payload.eip2930 ~chain_id:(w_of_int 2017) ~nonce:(nonce_of 3) ~gas_price:(w_of_int 7)
        ~gas_limit:60_000
        ~kind:(Transaction.Call (addr to_b))
        ~value:(w_of_int 255) ~data:(hex "010203") ~access_list:access_list_fixture;
    parity = false;
    r = "3048194c707e1dfa6c6111b808174ea031f9e20c215a249ed28a126b911dd853";
    s = "1995cceeb30605e2818187b9724a52ea29e98e5571a16fdb999c21132d86546e";
    signing_payload =
      "01f8978207e1030782ea609400000000000000000000000000000000000000ff81ff83010203f872f8599400000000000000000000000000000000000000fff842a00000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000ffd6943535353535353535353535353535353535353535c0";
    signing_hash = "0cab44879c47ab3751cdf68c8cb8d4ce98149acb1b076495acacc4ba022eb29e";
    encoded_2718 =
      "01f8da8207e1030782ea609400000000000000000000000000000000000000ff81ff83010203f872f8599400000000000000000000000000000000000000fff842a00000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000ffd6943535353535353535353535353535353535353535c080a03048194c707e1dfa6c6111b808174ea031f9e20c215a249ed28a126b911dd853a01995cceeb30605e2818187b9724a52ea29e98e5571a16fdb999c21132d86546e";
    tx_hash = "459898cef132ef21291f5d7addbf13d8a074fa99d2432054b68745b95d331c0a";
    sender = sender_key;
  }

let eip2930_empty_access_list =
  {
    name = "eip2930_empty_access_list";
    payload =
      Tx_payload.eip2930 ~chain_id:(w_of_int 1) ~nonce:(nonce_of 0) ~gas_price:U256.zero
        ~gas_limit:21_000
        ~kind:(Transaction.Call (addr to_a))
        ~value:U256.zero ~data:"" ~access_list:[];
    parity = false;
    r = "4f70ba512f84ca0a2c651abb9242aecf57bdf606b273b2d7fad911ab7415d65a";
    s = "4b4b3ffa1d012826117b4b93009d5120e2ddc23a0460f0ca6ced75d294ccd66f";
    signing_payload = "01de0180808252089435353535353535353535353535353535353535358080c0";
    signing_hash = "9c0bf6cf306da1cf4348af18e6d955fda89d87010bb0a1ef555c0e4c7905b966";
    encoded_2718 =
      "01f8610180808252089435353535353535353535353535353535353535358080c080a04f70ba512f84ca0a2c651abb9242aecf57bdf606b273b2d7fad911ab7415d65aa04b4b3ffa1d012826117b4b93009d5120e2ddc23a0460f0ca6ced75d294ccd66f";
    tx_hash = "bea6ad9cbe1c1cae78eabded7ee0dcebdf28eb77e210697f2e49c90ac64848e1";
    sender = sender_key2;
  }

let eip1559_with_access_list =
  {
    name = "eip1559_with_access_list";
    payload =
      Tx_payload.eip1559 ~chain_id:(w_of_int 2017) ~nonce:(nonce_of 42)
        ~max_priority_fee_per_gas:(w_of_int 2_000_000_000)
        ~max_fee_per_gas:(w_of_int 100_000_000_000)
        ~gas_limit:90_000
        ~kind:(Transaction.Call (addr to_a))
        ~value:(w_of_int 12_345) ~data:(hex "cafe") ~access_list:access_list_fixture;
    parity = true;
    r = "63650d80b610613b9d2eebb8811cc6a06c6e7b20805856bd00c28dd85c73cc98";
    s = "57a90d126c1e68b34d60547a7de610e6e53c8f2864ae49cdfd13f244a7b7f058";
    signing_payload =
      "02f8a28207e12a847735940085174876e80083015f9094353535353535353535353535353535353535353582303982cafef872f8599400000000000000000000000000000000000000fff842a00000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000ffd6943535353535353535353535353535353535353535c0";
    signing_hash = "80d456806e8ecc7c212a9ddb4a76add0d536a844aa023011aa5366a6bb06f5f0";
    encoded_2718 =
      "02f8e58207e12a847735940085174876e80083015f9094353535353535353535353535353535353535353582303982cafef872f8599400000000000000000000000000000000000000fff842a00000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000ffd6943535353535353535353535353535353535353535c001a063650d80b610613b9d2eebb8811cc6a06c6e7b20805856bd00c28dd85c73cc98a057a90d126c1e68b34d60547a7de610e6e53c8f2864ae49cdfd13f244a7b7f058";
    tx_hash = "231f0e8688dfc1263ae583be0e463e7acc3a6d71447b190cb0ab207e2554084a";
    sender = sender_key;
  }

let eip1559_create =
  {
    name = "eip1559_create";
    payload =
      Tx_payload.eip1559 ~chain_id:(w_of_int 1) ~nonce:(nonce_of 0)
        ~max_priority_fee_per_gas:U256.zero ~max_fee_per_gas:U256.zero ~gas_limit:21_000
        ~kind:Transaction.Create ~value:U256.zero ~data:"" ~access_list:[];
    parity = true;
    r = "93c19f25e301ad632834aef67cd38350cef6d19954cb4a89b2f1134d203b01a3";
    s = "780a96da226f1b73521af0be250c5ce8eef4b3cc50097862017661da77bcd66a";
    signing_payload = "02cb01808080825208808080c0";
    signing_hash = "9aa22984014995f8b2547f8ffaa74be06438f97535fca53b24a19169624ac563";
    encoded_2718 =
      "02f84e01808080825208808080c001a093c19f25e301ad632834aef67cd38350cef6d19954cb4a89b2f1134d203b01a3a0780a96da226f1b73521af0be250c5ce8eef4b3cc50097862017661da77bcd66a";
    tx_hash = "27b45439c77d0e55bb8690891fa3423013cd2ec71ebfd59c3072aa526bc76d03";
    sender = sender_key2;
  }

let cases =
  [
    legacy_eip155_spec_vector;
    legacy_pre155_no_chain_id;
    legacy_create;
    eip2930_with_access_list;
    eip2930_empty_access_list;
    eip1559_with_access_list;
    eip1559_create;
  ]

(* [calculate_transaction_root] over the first n fixtures, n = 1..7, in the order
   above. Entry 7 is the root over the whole set. *)
let prefix_roots =
  [
    "36cf58bec935fe50593ac7443cb728dd37dedac603d60fddfae59fd3bdbfcd7f";
    "48d95a51e8784e296562248f70168802d706bf5cf25f9d2e9c38f88b3be90243";
    "f8a90d782071390589ec73304c577391df331c5f540f18bae6e450b5d4e7fb80";
    "5ec9b96cfda1d128bbf945d2267448702131e9bd10f69e878b12bdf730735b45";
    "45611a56cb6c882eaaa489d4abd2785a9ff6dd7468caa63bfacf0b06eb876573";
    "79679ded442b3d446d3f2e05c07d695cacde750900f5b7e8c8dfb545e0eff519";
    "f549689c3d8427dc0d310f6990d5c9c744b90cbb6326409b2593644ef09ef711";
  ]
